matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      addons:
         homebrew:
             taps: zhaofeng-shu33/liblemonformula
script:
  - brew install --build-bottle glib-static
  - brew bottle glib-static
  - ls

