matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      addons:
         homebrew:
             taps: zhaofeng-shu33/liblemonformula
script:
  - brew uninstall --ignore-dependencies glib
  - brew install --build-bottle glib-static
  - brew bottle glib-static
  - mv glib-static--2.62.0_1.mojave.bottle.1.tar.gz glib-static-2.62.0_1.mojave.bottle.1.tar.gz
deploy:
  provider: bintry
  file: description.json
  user: zhaofeng-shu33
  key: $BINTRAY
  skip_cleanup: true